Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -1,30 +1,49 @@
-name: "Snyk Code Scan"
+name: Snyk SCA, Code, IaC and Container CLI monitor example
 
 on:
   push:
-    branches:
-      - master
+    branches: [ master ]
+  pull_request:
+    branches: [ master ]
 
 jobs:
-  Pipeline-Job:
-    # Configure Environment
-    name: 'Snyk Code Scan'
+  build:
+    name: Test and build
+    environment: snyk-npm
     runs-on: ubuntu-latest
-    env:
-      SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
 
-    steps:
-      # Checkout Code
-      - name: Checkout Code
-        uses: actions/checkout@v1
+strategy:
+  matrix:
+    node-version: [16.x]
 
-      # Install and Authenticate to Snyk
-      - name: Install Snyk & Authenticate
-        run: |
-          sudo npm install -g snyk
-          snyk auth ${SNYK_TOKEN}
-      # Run Snyk Code
-      - name: Run Snyk Code
-        run: |
-          snyk code test
-        continue-on-error: true
+    # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
+
+steps:
+  - uses: actions/checkout@v2
+  - name: Use Node.js ${{ matrix.node-version }}
+    uses: actions/setup-node@v2
+    with:
+      node-version: ${{ matrix.node-version }}
+      cache: 'npm'
+
+  - name: Setup Snyk + snyk-to-html # For information about the required commands for generating an HTML report see https://github.com/snyk/snyk-to-html
+    run: |
+      npm install snyk -g
+      npm install snyk-to-html -g
+      snyk auth ${{secrets.SNYK_AUTH}}
+
+  - name: Snyk Open Source # For testing and failing please add snyk test before snyk monitor
+    run: |
+      snyk monitor
+# For a list of additional available flags/options see: https://docs.snyk.io/snyk-cli/commands
+
+  - name: Snyk Code # Remove || true to fail if there are vulnerabilities
+    run: |
+      snyk code test || true
+  - name: Snyk Container # Rename your image, for testing and failing please add snyk container test before snyk container monitor
+    run: |
+      docker build . -t yourimage:tag
+      snyk container monitor yourimage:tag --file=Dockerfile
+  - name: Snyk IaC # Remove || true to fail if there are vulnerabilities
+    run: |
+      snyk iac test || true
